# Workaround for https://serverfault.com/questions/1099606/ansible-openssl-error-with-apt-module
- name: Upgrade pyOpenSSL
  ansible.builtin.pip:
    name: pyOpenSSL
    state: latest
    executable: pip3

- name: Install plotjuggler
  become: true
  ansible.builtin.apt:
    name:
      - ros-{{ rosdistro }}-plotjuggler-ros
    state: latest
    update_cache: true
