name: docker-build-and-push
description: ""

inputs:
  bake-target:
    description: ""
    required: true
  build-args:
    description: ""
    required: false
  tag-suffix:
    description: ""
    required: false

runs:
  using: composite
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install jq
      run: |
        sudo apt-get -y update
        sudo apt-get -y install jq
      shell: bash

    # workflow_dispatch: latest, date
    # schedule: latest, date
    # tag: semver
    - name: Set Docker tags
      id: set-docker-tags
      run: |
        tags=()
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          tags+=("latest")
          tags+=("{{date 'YYYYMMDD'}}")
        else
          tags+=("type=schedule,pattern=latest")
          tags+=("type=schedule,pattern={{date 'YYYYMMDD'}}")
          tags+=("type=semver,pattern={{version}}")
        fi

        # Workaround for multiline strings
        # https://github.community/t/set-output-truncates-multiline-strings/16852
        tags_multiline=$(printf "%s\n" "${tags[@]}")
        tags_multiline="${tags_multiline//'%'/'%25'}"
        tags_multiline="${tags_multiline//$'\n'/'%0A'}"
        tags_multiline="${tags_multiline//$'\r'/'%0D'}"

        echo ::set-output name=tags::$tags_multiline
      shell: bash

    - name: Docker meta for devel
      id: meta-devel
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-devel
        flavor: |
          latest=false
          suffix=${{ inputs.tag-suffix }}

    - name: Docker meta for prebuilt
      id: meta-prebuilt
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-prebuilt
        flavor: |
          latest=false
          suffix=-prebuilt${{ inputs.tag-suffix }}

    - name: Login to GitHub Container Registry
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    # For https://github.com/docker/buildx/issues/756
    - name: Merge json files
      run: |
        jq -s ".[0] * .[1]" \
          "${{ steps.meta-devel.outputs.bake-file }}" \
          "${{ steps.meta-prebuilt.outputs.bake-file }}" \
          > bake.json
      shell: bash

    - name: Build and push
      uses: docker/bake-action@v1
      with:
        push: ${{ github.ref_name == github.event.repository.default_branch }}
        files: |
          docker/${{ inputs.bake-target }}/docker-bake.hcl
          bake.json
        set: |
          ${{ inputs.build-args }}
