- hosts: localhost
  connection: local
  pre_tasks:
    - name: Print args
      ansible.builtin.debug:
        msg:
          - rosdistro: "{{ rosdistro }}"
          - rmw_implementation: "{{ rmw_implementation }}"
  roles:
    - role: autoware.dev_env.autoware_core
    - role: autoware.dev_env.ccache
    - role: autoware.dev_env.plotjuggler
    - role: autoware.dev_env.pre_commit
    - role: autoware.dev_env.ros2
    - role: autoware.dev_env.ros2_dev_tools
    - role: autoware.dev_env.rmw_implementation
