- hosts: localhost
  connection: local
  vars_prompt:
    - name: install_nvidia
      prompt: |-
        [Warning] Some Autoware components depend on the CUDA, cuDNN and TensorRT NVIDIA libraries which have end-user license agreements that should be reviewed before installation.
        Install NVIDIA libraries? [y/N]
      private: false
  pre_tasks:
    - name: Print args
      ansible.builtin.debug:
        msg:
          - rosdistro: "{{ rosdistro }}"
          - rmw_implementation: "{{ rmw_implementation }}"
          - cuda_version: "{{ cuda_version }}"
          - cudnn_version: "{{ cudnn_version }}"
          - tensorrt_version: "{{ tensorrt_version }}"
    - name: Show a warning if the NVIDIA libraries will not be installed
      ansible.builtin.pause:
        seconds: 10
        prompt: |
          [Warning] Skipping installation of NVIDIA libraries. Please manually install them if you plan to use any dependent components.
      when: install_nvidia != 'y'
  roles:
    # Core
    - role: autoware.dev_env.autoware_core
    - role: autoware.dev_env.ccache
    - role: autoware.dev_env.plotjuggler
    - role: autoware.dev_env.pre_commit
    - role: autoware.dev_env.ros2
    - role: autoware.dev_env.ros2_dev_tools
    - role: autoware.dev_env.rmw_implementation

    # Universe
    - role: autoware.dev_env.autoware_universe
    - role: autoware.dev_env.cuda
      when: install_nvidia == 'y'
    - role: autoware.dev_env.pacmod
      when: rosdistro == 'galactic'
    - role: autoware.dev_env.tensorrt
      when: install_nvidia == 'y'
