name: update-docker-manifest

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update-docker-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Combine multi arch images for 'autoware-universe'
        uses: ./.github/actions/combine-multi-arch-images
        with:
          package-name: autoware-universe

      - name: Create alias from 'autoware-universe:{rosdistro}-latest' to 'autoware-universe:latest'
        uses: ./.github/actions/create-main-distro-alias
        with:
          package-name: autoware-universe
          rosdistro: galactic
          tag-name: latest

      - name: Create alias from 'autoware-universe:{rosdistro}-latest-prebuilt' to 'autoware-universe:latest-prebuilt'
        uses: ./.github/actions/create-main-distro-alias
        with:
          package-name: autoware-universe
          rosdistro: galactic
          tag-name: latest-prebuilt

      - name: Create alias from 'autoware-universe:{rosdistro}-latest-cuda' to 'autoware-universe:latest-cuda'
        uses: ./.github/actions/create-main-distro-alias
        with:
          package-name: autoware-universe
          rosdistro: galactic
          tag-name: latest-cuda

      - name: Create alias from 'autoware-universe:{rosdistro}-latest-prebuilt-cuda' to 'autoware-universe:latest-prebuilt-cuda'
        uses: ./.github/actions/create-main-distro-alias
        with:
          package-name: autoware-universe
          rosdistro: galactic
          tag-name: latest-prebuilt-cuda
